/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import islandScene from '../assets/3d/island.glb';

import { a } from '@react-spring/three'

const Island = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/ImageToStl.com_kiit-dark.glb"
  );
  const { actions } = useAnimations(animations, group);
  const islandRef = useRef();
  return (
    <a.group ref={islandRef} {...props} >
      <a.group name="Scene">
        <mesh
          name="Plane001"
          
          
          geometry={nodes.Plane001.geometry}
          material={materials["Material.005"]}
          position={[-759.272, 424.909, 3161.941]}
          rotation={[Math.PI, -1.321, Math.PI]}
          scale={[37.48, 73.615, 742.471]}
        >
          <mesh
            name="Cube"
            
            
            geometry={nodes.Cube.geometry}
            material={materials.Material}
            position={[-0.267, -3.025, -0.03]}
            scale={[1.756, 0.894, 1.177]}
          />
          <mesh
            name="Plane"
            
            
            geometry={nodes.Plane.geometry}
            material={materials["Material.001"]}
            position={[0.811, 1.676, 0.378]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.203, 4.024, 2.049]}
          />
          <mesh
            name="Plane002"
            
            
            geometry={nodes.Plane002.geometry}
            material={materials["Material.005"]}
            position={[0.028, 1.853, 0.002]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[2.227, 4.393, 0.934]}
          />
          <mesh
            name="Text"
            
            
            geometry={nodes.Text.geometry}
            material={materials["Material.003"]}
            position={[1.003, -0.064, 0.763]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.753, 14.92, 7.596]}
          />
          <mesh
            name="Text001"
            
            
            geometry={nodes.Text001.geometry}
            material={materials["Material.004"]}
            position={[1.308, 0.037, 0.074]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.688, 13.63, 6.94]}
          />
        </mesh>
        <group
          name="Wind"
          position={[-175.103, 2134.495, -1125.848]}
          rotation={[1.553, 0, 0]}
          scale={278.349}
        />
        <group
          name="Cube002"
          position={[0, 1.315, 0]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.753}
        >
          <mesh
            name="Cube004_1"
            
            
            geometry={nodes.Cube004_1.geometry}
            material={materials.robot}
          />
          <mesh
            name="Cube004_2"
            
            
            geometry={nodes.Cube004_2.geometry}
            material={materials.Black}
          />
          <mesh
            name="Cube004_3"
            
            
            geometry={nodes.Cube004_3.geometry}
            material={materials["Material.011"]}
          />
          <mesh
            name="Cube004_4"
            
            
            geometry={nodes.Cube004_4.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            name="Cube004_5"
            
            
            geometry={nodes.Cube004_5.geometry}
            material={materials["Material.025"]}
          />
          <mesh
            name="Cube004_6"
            
            
            geometry={nodes.Cube004_6.geometry}
            material={materials["Material.027"]}
          />
        </group>
        <group
          name="Cube001"
          position={[0, 1.315, 0]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.753}
        >
          <mesh
            name="Cube005"
            
            
            geometry={nodes.Cube005.geometry}
            material={materials["robot.001"]}
          />
          <mesh
            name="Cube005_1"
            
            
            geometry={nodes.Cube005_1.geometry}
            material={materials["Black.001"]}
          />
          <mesh
            name="Cube005_2"
            
            
            geometry={nodes.Cube005_2.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            name="Cube005_3"
            
            
            geometry={nodes.Cube005_3.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            name="Cube005_4"
            
            
            geometry={nodes.Cube005_4.geometry}
            material={materials["Material.032"]}
          />
          <mesh
            name="Cube005_5"
            
            
            geometry={nodes.Cube005_5.geometry}
            material={materials["Material.034"]}
          />
        </group>
        <mesh
          name="Cylinder"
          
          
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.010"]}
          position={[-151.955, 48.93, 391.2]}
          scale={[3395.003, 125.948, 3395.003]}
        />
        <mesh
          name="building001"
          
          
          geometry={nodes.building001.geometry}
          material={materials["Material.009"]}
          position={[641.215, 266.732, 3070.28]}
          rotation={[0, 0.827, 0]}
          scale={[340.311, 127.304, 173.025]}
        >
          <mesh
            name="building"
            
            
            geometry={nodes.building.geometry}
            material={materials["Material.007"]}
            position={[0, 0.061, 0]}
          />
          <mesh
            name="logo"
            
            
            geometry={nodes.logo.geometry}
            material={materials["Material.006"]}
            position={[0.882, 8.752, 1.365]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.013, 0.026, 0.036]}
          />
          <mesh
            name="Text002"
            
            
            geometry={nodes.Text002.geometry}
            material={materials["Material.006"]}
            position={[0.49, 5.331, 1.386]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.278, 0.547, 0.743]}
          />
          <mesh
            name="Text003"
            
            
            geometry={nodes.Text003.geometry}
            material={materials["Material.006"]}
            position={[0.478, 5.96, 1.41]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.254, 0.5, 0.68]}
          />
        </mesh>
        <group
          name="Circle003"
          position={[-1698.819, 520.237, -1555.806]}
          rotation={[Math.PI, -0.337, Math.PI]}
          scale={638.873}
        >
          <mesh
            name="Circle003_1"
            
            
            geometry={nodes.Circle003_1.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            name="Circle003_2"
            
            
            geometry={nodes.Circle003_2.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            name="Circle003_3"
            
            
            geometry={nodes.Circle003_3.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            name="logo002"
            
            
            geometry={nodes.logo002.geometry}
            material={materials["Material.006"]}
            position={[0.974, 0.64, -0.05]}
            rotation={[Math.PI / 2, 0, -0.602]}
            scale={0.007}
          />
          <mesh
            name="logo003"
            
            
            geometry={nodes.logo003.geometry}
            material={materials["Material.006"]}
            position={[3.263, 0.641, -3.401]}
            rotation={[Math.PI / 2, 0, -1.331]}
            scale={0.007}
          />
          <group
            name="Plane006"
            position={[2.794, 0.796, -4.15]}
            rotation={[Math.PI, -1.441, Math.PI]}
            scale={0.547}
          >
            <mesh
              name="Plane013_1"
              
              
              geometry={nodes.Plane013_1.geometry}
              material={materials["Material.015"]}
            />
            <mesh
              name="Plane013_2"
              
              
              geometry={nodes.Plane013_2.geometry}
              material={materials["Material.016"]}
            />
            <mesh
              name="Plane013_3"
              
              
              geometry={nodes.Plane013_3.geometry}
              material={materials["Material.023"]}
            />
          </group>
          <mesh
            name="Text005"
            
            
            geometry={nodes.Text005.geometry}
            material={materials["Material.006"]}
            position={[2.217, -0.146, -1.036]}
            rotation={[1.563, -0.005, -1.003]}
            scale={0.14}
          />
        </group>
        <mesh
          name="Circle006"
          
          
          geometry={nodes.Circle006.geometry}
          material={materials["Material.036"]}
          position={[-1698.819, 520.237, -1555.806]}
          rotation={[Math.PI, -0.337, Math.PI]}
          scale={656.334}
        />
        <mesh
          name="Circle002"
          
          
          geometry={nodes.Circle002.geometry}
          material={materials["Material.008"]}
          position={[1339.562, 1380.867, -907.913]}
          rotation={[0, -0.561, 0]}
          scale={1267.024}
        >
          <mesh
            name="logo001"
            
            
            geometry={nodes.logo001.geometry}
            material={materials["Material.006"]}
            position={[0.822, -0.072, -0.611]}
            rotation={[Math.PI / 2, 0, -2.291]}
            scale={0.003}
          />
          <mesh
            name="Text004"
            
            
            geometry={nodes.Text004.geometry}
            material={materials["Material.006"]}
            position={[0.772, -0.248, -0.668]}
            rotation={[Math.PI / 2, 0, -2.306]}
            scale={0.038}
          />
        </mesh>
        <mesh
          name="Circle005"
          
          
          geometry={nodes.Circle005.geometry}
          material={materials["Material.035"]}
          position={[1339.562, 1380.867, -907.913]}
          rotation={[0, -0.561, 0]}
          scale={1267.024}
        />
        <mesh
          name="Circle004"
          
          
          geometry={nodes.Circle004.geometry}
          material={materials["Material.022"]}
          position={[-242.928, 165.197, 531.392]}
          scale={-366.63}
        >
          <mesh
            name="Cone"
            
            
            geometry={nodes.Cone.geometry}
            material={materials["Material.021"]}
            position={[-0.032, -6.77, -0.049]}
            scale={[-0.055, -0.128, -0.055]}
          />
          <mesh
            name="Cylinder001"
            
            
            geometry={nodes.Cylinder001.geometry}
            material={materials["Material.019"]}
            position={[-0.038, -3.334, -0.043]}
            scale={[-0.057, -3.121, -0.057]}
          />
          <mesh
            name="Plane010"
            
            
            geometry={nodes.Plane010.geometry}
            material={materials["Material.017"]}
            position={[-0.012, -5.541, -1.619]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={[-1.567, -0.668, -0.855]}
          />
          <mesh
            name="Sphere"
            
            
            geometry={nodes.Sphere.geometry}
            material={materials["Material.020"]}
            position={[-0.032, -6.566, -0.049]}
            scale={-0.108}
          />
        </mesh>
        <mesh
          name="Cube010"
          
          
          geometry={nodes.Cube010.geometry}
          material={materials.Orange}
          position={[338.45, 412.676, 3354.247]}
          rotation={[Math.PI, -1.142, Math.PI]}
          scale={[34.704, 12.466, 34.704]}
        />
        <mesh
          name="Cylinder006"
          
          
          geometry={nodes.Cylinder006.geometry}
          material={materials.Orange}
          position={[338.45, 412.676, 3354.247]}
          rotation={[Math.PI, -1.142, Math.PI]}
          scale={[8.483, 34.704, 8.483]}
        />
        <mesh
          name="Cylinder008"
          
          
          geometry={nodes.Cylinder008.geometry}
          material={materials.Orange}
          position={[338.45, 412.676, 3354.247]}
          rotation={[Math.PI, -1.142, Math.PI]}
          scale={[8.483, 34.704, 8.483]}
        />
        <mesh
          name="Sphere001"
          
          
          geometry={nodes.Sphere001.geometry}
          material={materials.Orange}
          position={[338.45, 412.676, 3354.247]}
          rotation={[Math.PI / 2, 0, 0.429]}
          scale={90.098}
        />
        <mesh
          name="Sphere002"
          
          
          geometry={nodes.Sphere002.geometry}
          material={materials["Black.002"]}
          position={[338.45, 412.676, 3354.247]}
          rotation={[Math.PI / 2, 0, 0.429]}
          scale={32.985}
        />
        <mesh
          name="Sphere004"
          
          
          geometry={nodes.Sphere004.geometry}
          material={materials["Black.002"]}
          position={[338.45, 412.676, 3354.247]}
          rotation={[Math.PI / 2, 0, 0.429]}
          scale={20.164}
        />
        <mesh
          name="Sphere005"
          
          
          geometry={nodes.Sphere005.geometry}
          material={materials["Black.002"]}
          position={[338.45, 412.676, 3354.247]}
          rotation={[Math.PI / 2, 0, 0.429]}
          scale={18.942}
        />
        <mesh
          name="Sphere006"
          
          
          geometry={nodes.Sphere006.geometry}
          material={materials["Black.002"]}
          position={[338.62, 411.948, 3354.247]}
          rotation={[Math.PI, -1.142, Math.PI]}
          scale={22.63}
        />
        <mesh
          name="Circle007"
          
          
          geometry={nodes.Circle007.geometry}
          material={nodes.Circle007.material}
          position={[-1057.198, 148.869, 2079.927]}
          scale={36.612}
        />
        <mesh
          name="Plane011"
          
          
          geometry={nodes.Plane011.geometry}
          material={nodes.Plane011.material}
          position={[-1057.198, 1241.049, 2154.729]}
          rotation={[Math.PI / 2, 0, 0.239]}
          scale={[443.655, 99.545, 267.455]}
        />
        <mesh
          name="Cube003"
          
          
          geometry={nodes.Cube003.geometry}
          material={nodes.Cube003.material}
          position={[-1042.207, 1093.441, 2046.206]}
          scale={[145.164, 72.946, 17.423]}
        />
        <a.group
          name="Cube004"
          position={[0, 1.315, 0]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.753}
        >
          <mesh
            name="Cube006"
            
            
            geometry={nodes.Cube006.geometry}
            material={materials["robot.002"]}
          />
          <mesh
            name="Cube006_1"
            
            
            geometry={nodes.Cube006_1.geometry}
            material={materials["Black.003"]}
          />
          <mesh
            name="Cube006_2"
            
            
            geometry={nodes.Cube006_2.geometry}
            material={materials["Material.082"]}
          />
          <mesh
            name="Cube006_3"
            
            
            geometry={nodes.Cube006_3.geometry}
            material={materials["Material.083"]}
          />
          <mesh
            name="Cube006_4"
            
            
            geometry={nodes.Cube006_4.geometry}
            material={materials["Material.085"]}
          />
          <mesh
            name="Cube006_5"
            
            
            geometry={nodes.Cube006_5.geometry}
            material={materials["Material.087"]}
          />
        </a.group>
        <mesh
          name="Plane012"
          
          
          geometry={nodes.Plane012.geometry}
          material={nodes.Plane012.material}
          position={[1450.39, 1793.874, 1607.072]}
          rotation={[Math.PI / 2, 0, -0.778]}
          scale={[443.655, 99.545, 267.455]}
        />
        <mesh
          name="Cylinder002"
          
          
          geometry={nodes.Cylinder002.geometry}
          material={nodes.Cylinder002.material}
          position={[1587.618, 1409.26, 1784.467]}
          rotation={[0, -0.877, 1.47]}
          scale={25.023}
        />
        <mesh
          name="Plane013"
          
          
          geometry={nodes.Plane013.geometry}
          material={nodes.Plane013.material}
          position={[1388.004, 1746.549, -994.396]}
          rotation={[Math.PI / 2, 0, -2.497]}
          scale={[443.655, 99.545, 267.455]}
        />
        <mesh
          name="Plane014"
          
          
          geometry={nodes.Plane014.geometry}
          material={nodes.Plane014.material}
          position={[-2340.359, 1666.359, -169.971]}
          rotation={[Math.PI / 2, 0, 1.894]}
          scale={[443.655, 99.545, 267.455]}
        />
      </a.group>
    </a.group>
  );
}

export default Island;